/*
 * Hivelocity API
 *
 * Interact with Hivelocity
 *
 * API version: 2.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type Ticket struct {
	Status string `json:"status,omitempty"`
	Subject string `json:"subject,omitempty"`
	Queue string `json:"queue,omitempty"`
	Updated float32 `json:"updated,omitempty"`
	Opened float32 `json:"opened,omitempty"`
	ServiceId float32 `json:"serviceId,omitempty"`
	Client *Client `json:"client,omitempty"`
	Priority string `json:"priority,omitempty"`
	Id float32 `json:"id,omitempty"`
	Posts float32 `json:"posts,omitempty"`
	Contact *ContactDump `json:"contact,omitempty"`
	Body string `json:"body,omitempty"`
	NewReply bool `json:"newReply,omitempty"`
	MetaData interface{} `json:"metaData,omitempty"`
	Replies []TicketPost `json:"replies,omitempty"`
	ClientId float32 `json:"clientId,omitempty"`
	ContactId float32 `json:"contactId,omitempty"`
	Duration float32 `json:"duration,omitempty"`
	InternalTicket float32 `json:"internalTicket,omitempty"`
}
