/*
 * Hivelocity API
 *
 * Interact with Hivelocity
 *
 * API version: 2.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ProductMatch struct {
	HwInfo *Hardware `json:"hwInfo,omitempty"`
	DeviceId int32 `json:"deviceId,omitempty"`
	LocationCode string `json:"locationCode,omitempty"`
	MarketClients []string `json:"marketClients,omitempty"`
	LshwOutput interface{} `json:"lshwOutput,omitempty"`
}
