/*
 * Hivelocity API for Partners
 *
 * Interact with Hivelocity
 *
 * API version: 2.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type Device struct {
	DeviceId int32 `json:"deviceId,omitempty"`
	Name string `json:"name"`
	Status string `json:"status,omitempty"`
	DeviceType string `json:"deviceType,omitempty"`
	DeviceTypeGroup string `json:"deviceTypeGroup,omitempty"`
	PowerStatus string `json:"powerStatus,omitempty"`
	HasCancellation bool `json:"hasCancellation,omitempty"`
	IsManaged bool `json:"isManaged,omitempty"`
	IsReload bool `json:"isReload,omitempty"`
	MonitorsUp int32 `json:"monitorsUp,omitempty"`
	MonitorsTotal int32 `json:"monitorsTotal,omitempty"`
	ManagedAlertsTotal int32 `json:"managedAlertsTotal,omitempty"`
	Hostname string `json:"hostname,omitempty"`
	IpmiEnabled bool `json:"ipmiEnabled,omitempty"`
	DisplayedTags []interface{} `json:"displayedTags,omitempty"`
	Tags []string `json:"tags,omitempty"`
	Location interface{} `json:"location,omitempty"`
	PrimaryIp string `json:"primaryIp,omitempty"`
	IpmiAddress string `json:"ipmiAddress,omitempty"`
	ServiceMonitors []string `json:"serviceMonitors,omitempty"`
	BillingInfo interface{} `json:"billingInfo,omitempty"`
	ServicePlan int32 `json:"servicePlan,omitempty"`
	LastInvoiceId int32 `json:"lastInvoiceId,omitempty"`
	SelfProvisioning bool `json:"selfProvisioning,omitempty"`
	Metadata interface{} `json:"metadata,omitempty"`
}
