/*
 * Hivelocity API
 *
 * Interact with Hivelocity
 *
 * API version: 2.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type DomainReturn struct {
	DirectsTo string `json:"directsTo"`
	DomainId int32 `json:"domainId"`
	Summary interface{} `json:"summary,omitempty"`
	Name string `json:"name"`
}
