/*
 * Hivelocity API
 *
 * Interact with Hivelocity
 *
 * API version: 2.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type Stock struct {
	ProductName string `json:"product_name,omitempty"`
	ProductMonthlyPrice float32 `json:"product_monthly_price,omitempty"`
	ProductBiennialPrice float32 `json:"product_biennial_price,omitempty"`
	ProductId int32 `json:"product_id,omitempty"`
	ProductDrive string `json:"product_drive,omitempty"`
	ProductCpuCores string `json:"product_cpu_cores,omitempty"`
	ProductDisplayPrice float32 `json:"product_display_price,omitempty"`
	ProductHourlyPrice float32 `json:"product_hourly_price,omitempty"`
	ProductTriennialPrice float32 `json:"product_triennial_price,omitempty"`
	MonthlyLocationPremium float32 `json:"monthly_location_premium,omitempty"`
	Core bool `json:"core,omitempty"`
	ProductOnSale bool `json:"product_on_sale,omitempty"`
	Stock string `json:"stock,omitempty"`
	ProductQuarterlyPrice float32 `json:"product_quarterly_price,omitempty"`
	HourlyLocationPremium float32 `json:"hourly_location_premium,omitempty"`
	ProductAnnuallyPrice float32 `json:"product_annually_price,omitempty"`
	ProductCpu string `json:"product_cpu,omitempty"`
	Location string `json:"location,omitempty"`
	Edge bool `json:"edge,omitempty"`
	ProductMemory string `json:"product_memory,omitempty"`
	ProductSemiAnnuallyPrice float32 `json:"product_semi_annually_price,omitempty"`
	ProductBandwidth string `json:"product_bandwidth,omitempty"`
	ProductOriginalPrice float32 `json:"product_original_price,omitempty"`
}
