/*
 * Hivelocity API for Partners
 *
 * Interact with Hivelocity
 *
 * API version: 2.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type VlanCreate struct {
	Description string `json:"description,omitempty"`
	DeviceIds []int32 `json:"deviceIds,omitempty"`
}
