/*
 * Hivelocity API
 *
 * Interact with Hivelocity
 *
 * API version: 2.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type DeviceEvent struct {
	Time int32 `json:"time,omitempty"`
	Action string `json:"action,omitempty"`
}
