/*
 * Hivelocity API
 *
 * Interact with Hivelocity
 *
 * API version: 2.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type InvoiceDetailsServiceItems struct {
	ServiceId int32 `json:"serviceId,omitempty"`
	UnitPrice float32 `json:"unitPrice,omitempty"`
	DateRange *interface{} `json:"dateRange,omitempty"`
	Quantity int32 `json:"quantity,omitempty"`
	Description string `json:"description,omitempty"`
}
