/*
 * Hivelocity API
 *
 * Interact with Hivelocity
 *
 * API version: 2.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type TicketAttach struct {
	Name string `json:"name,omitempty"`
	Id float32 `json:"id,omitempty"`
}
