/*
 * Hivelocity API
 *
 * Interact with Hivelocity
 *
 * API version: 2.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type CancellationCreate struct {
	ServiceId int32 `json:"serviceId"`
	DeviceId int32 `json:"deviceId,omitempty"`
	Reason string `json:"reason"`
}
