/*
 * Hivelocity API
 *
 * Interact with Hivelocity
 *
 * API version: 2.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ContactDump struct {
	FullName string `json:"fullName"`
	Email string `json:"email"`
	IsClient bool `json:"isClient,omitempty"`
	Description string `json:"description,omitempty"`
	ClientId int32 `json:"clientId,omitempty"`
	Phone string `json:"phone,omitempty"`
	ContactId int32 `json:"contactId,omitempty"`
	Active int32 `json:"active"`
}
