/*
 * Hivelocity API
 *
 * Interact with Hivelocity
 *
 * API version: 2.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type IpmiInfo struct {
	DeviceAvailable string `json:"deviceAvailable,omitempty"`
	IpmiVersion string `json:"ipmiVersion,omitempty"`
	Bridge string `json:"bridge,omitempty"`
	ProductId string `json:"productId,omitempty"`
	DeviceRevision string `json:"deviceRevision,omitempty"`
	ManufacturerId string `json:"manufacturerId,omitempty"`
	SensorDevice string `json:"sensorDevice,omitempty"`
	AuxFirmwareRevInfo string `json:"auxFirmwareRevInfo,omitempty"`
	FruInventoryDevice string `json:"fruInventoryDevice,omitempty"`
	ChassisDevice string `json:"chassisDevice,omitempty"`
	FirmwareRevision string `json:"firmwareRevision,omitempty"`
	DeviceSDRs string `json:"deviceSDRs,omitempty"`
	SelDevice string `json:"selDevice,omitempty"`
	IpmbEventGenerator string `json:"ipmbEventGenerator,omitempty"`
	SdrRepositoryDevice string `json:"sdrRepositoryDevice,omitempty"`
	DeviceId string `json:"deviceId,omitempty"`
	IpmbEventReceiver string `json:"ipmbEventReceiver,omitempty"`
}
