/*
 * Hivelocity API
 *
 * Interact with Hivelocity
 *
 * API version: 2.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type AaaaRecordCreate struct {
	Ttl int32 `json:"ttl"`
	Address string `json:"address"`
	Name string `json:"name"`
}
