/*
 * Hivelocity API
 *
 * Interact with Hivelocity
 *
 * API version: 2.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ProductMatch struct {
	SpsOnly bool `json:"spsOnly,omitempty"`
	LshwOutput *interface{} `json:"lshwOutput,omitempty"`
}
