/*
 * Hivelocity API
 *
 * Interact with Hivelocity
 *
 * API version: 2.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ProfileUpdate struct {
	First string `json:"first,omitempty"`
	Phone string `json:"phone,omitempty"`
	City string `json:"city,omitempty"`
	State string `json:"state,omitempty"`
	Country string `json:"country,omitempty"`
	Zip string `json:"zip,omitempty"`
	Address string `json:"address,omitempty"`
	Last string `json:"last,omitempty"`
	Email string `json:"email,omitempty"`
	FullName string `json:"full_name,omitempty"`
	Company string `json:"company,omitempty"`
}
