/*
 * Hivelocity API for Partners
 *
 * Interact with Hivelocity
 *
 * API version: 2.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type RecordValue struct {
	Address string `json:"address,omitempty"`
	Id int32 `json:"id,omitempty"`
}
