/*
 * Hivelocity API
 *
 * Interact with Hivelocity
 *
 * API version: 2.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type Invoice struct {
	Id int32 `json:"id,omitempty"`
	Amount float32 `json:"amount,omitempty"`
	AmountUnpaid float32 `json:"amountUnpaid,omitempty"`
	ClientId int32 `json:"clientId,omitempty"`
	Created int32 `json:"created,omitempty"`
	DatePaid int32 `json:"datePaid,omitempty"`
	Due int32 `json:"due,omitempty"`
	Sent int32 `json:"sent,omitempty"`
	Status string `json:"status,omitempty"`
}
