/*
 * Hivelocity API for Partners
 *
 * Interact with Hivelocity
 *
 * API version: 2.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type MxValue struct {
	Exchange string `json:"exchange"`
	Preference int32 `json:"preference"`
	Id int32 `json:"id"`
}
