/*
 * Hivelocity API for Partners
 *
 * Interact with Hivelocity
 *
 * API version: 2.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type CityStateCountry struct {
	State string `json:"state,omitempty"`
	City string `json:"city,omitempty"`
	Country string `json:"country,omitempty"`
}
