/*
 * Hivelocity API for Partners
 *
 * Interact with Hivelocity
 *
 * API version: 2.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type UpdateDevicesIpmiThresholds struct {
	DeviceIds []int32 `json:"device_ids"`
	Thresholds *interface{} `json:"thresholds"`
}
