/*
 * Hivelocity API for Partners
 *
 * Interact with Hivelocity
 *
 * API version: 2.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type Option struct {
	Tags []string `json:"tags,omitempty"`
	MonthlyPrice float32 `json:"monthlyPrice,omitempty"`
	Id int32 `json:"id,omitempty"`
	Currency string `json:"currency,omitempty"`
	Expressions []string `json:"expressions,omitempty"`
	Name string `json:"name,omitempty"`
}
