/*
 * Hivelocity API
 *
 * Interact with Hivelocity
 *
 * API version: 2.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type Credit struct {
	Id int32 `json:"id,omitempty"`
	Amount float32 `json:"amount,omitempty"`
	Balance float32 `json:"balance,omitempty"`
	ClientId int32 `json:"clientId,omitempty"`
	Created int32 `json:"created,omitempty"`
	OrderId int32 `json:"orderId,omitempty"`
	Reason string `json:"reason,omitempty"`
	Status string `json:"status,omitempty"`
	BillingInfoId int32 `json:"billingInfoId,omitempty"`
}
