/*
 * Hivelocity API
 *
 * Interact with Hivelocity
 *
 * API version: 2.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type TicketCreateReply struct {
	Subject string `json:"subject,omitempty"`
	Headers string `json:"headers,omitempty"`
	Hidden float32 `json:"hidden,omitempty"`
	Encrypted string `json:"encrypted,omitempty"`
	Body string `json:"body"`
	ContactId float32 `json:"contactId,omitempty"`
	Date float32 `json:"date,omitempty"`
	Attachments []interface{} `json:"attachments,omitempty"`
	Recipient string `json:"recipient,omitempty"`
	Cc string `json:"cc,omitempty"`
	ReplyTo string `json:"replyTo,omitempty"`
	Type_ float32 `json:"type,omitempty"`
}
