/*
 * Hivelocity API for Partners
 *
 * Interact with Hivelocity
 *
 * API version: 2.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ARecordCreate struct {
	Name string `json:"name"`
	Address string `json:"address,omitempty"`
	Ttl int32 `json:"ttl"`
}
