/*
 * Hivelocity API
 *
 * Interact with Hivelocity
 *
 * API version: 2.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type DeviceInterface struct {
	Status int32 `json:"status,omitempty"`
	Name string `json:"name,omitempty"`
	InterfaceId int32 `json:"interfaceId,omitempty"`
	Private bool `json:"private,omitempty"`
	SwitchName string `json:"switchName,omitempty"`
	SwitchPort string `json:"switchPort,omitempty"`
}
