/*
 * Hivelocity API
 *
 * Interact with Hivelocity
 *
 * API version: 2.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type BareMetalDeviceCreate struct {
	LocationName string `json:"locationName"`
	VlanId int32 `json:"vlanId,omitempty"`
	Script string `json:"script,omitempty"`
	ProductId int32 `json:"productId"`
	Period string `json:"period,omitempty"`
	PublicSshKeyId int32 `json:"publicSshKeyId,omitempty"`
	OsName string `json:"osName"`
	Hostname string `json:"hostname"`
}
