/*
 * Hivelocity API
 *
 * Interact with Hivelocity
 *
 * API version: 2.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type BillingInfo struct {
	Id int32 `json:"id,omitempty"`
	City string `json:"city,omitempty"`
	Company string `json:"company,omitempty"`
	Zip string `json:"zip,omitempty"`
	PaymentType string `json:"paymentType,omitempty"`
	CcNum string `json:"ccNum,omitempty"`
	AchBank string `json:"achBank,omitempty"`
	AchAccount string `json:"achAccount,omitempty"`
	CcType string `json:"ccType,omitempty"`
	AchAba string `json:"achAba,omitempty"`
	First string `json:"first,omitempty"`
	Address string `json:"address,omitempty"`
	CcExpire string `json:"ccExpire,omitempty"`
	State string `json:"state,omitempty"`
	Last string `json:"last,omitempty"`
	ClientId int32 `json:"clientId,omitempty"`
	Email string `json:"email,omitempty"`
	AchType string `json:"achType,omitempty"`
	Phone string `json:"phone,omitempty"`
	Country string `json:"country,omitempty"`
	Status int32 `json:"status,omitempty"`
}
