/*
 * Hivelocity API
 *
 * Interact with Hivelocity
 *
 * API version: 2.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type Product struct {
	IsSps bool `json:"isSps,omitempty"`
	Sale int32 `json:"sale,omitempty"`
	OriginalPrice float32 `json:"originalPrice,omitempty"`
	Drive string `json:"drive,omitempty"`
	Stock int32 `json:"stock,omitempty"`
	Cpu string `json:"cpu,omitempty"`
	Discount float32 `json:"discount,omitempty"`
	Memory string `json:"memory,omitempty"`
	PlanId int32 `json:"planId,omitempty"`
	Name string `json:"name,omitempty"`
	New int32 `json:"new,omitempty"`
	Id int32 `json:"id,omitempty"`
}
