/*
 * Hivelocity API for Partners
 *
 * Interact with Hivelocity
 *
 * API version: 2.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type SshKeyUpdate struct {
	Name string `json:"name,omitempty"`
	PublicKey string `json:"publicKey,omitempty"`
}
