/*
 * Hivelocity API
 *
 * Interact with Hivelocity
 *
 * API version: 2.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type InvoicePdf struct {
	InvoiceId int32 `json:"invoiceId,omitempty"`
	PdfData string `json:"pdfData,omitempty"`
}
