/*
 * Hivelocity API
 *
 * Interact with Hivelocity
 *
 * API version: 2.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type TicketCreate struct {
	Body string `json:"body,omitempty"`
	Assignment float32 `json:"assignment,omitempty"`
	Source float32 `json:"source,omitempty"`
	Subject string `json:"subject"`
	Status string `json:"status,omitempty"`
	Priority float32 `json:"priority,omitempty"`
	Queue string `json:"queue"`
}
