/*
 * Hivelocity API for Partners
 *
 * Interact with Hivelocity
 *
 * API version: 2.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type SingleMxRecordCreate struct {
	Exchange string `json:"exchange"`
	Ttl int32 `json:"ttl"`
	Name string `json:"name"`
	Preference int32 `json:"preference"`
}
