/*
 * Hivelocity API
 *
 * Interact with Hivelocity
 *
 * API version: 2.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type WebhookUpdate struct {
	Name string `json:"name,omitempty"`
	Event string `json:"event,omitempty"`
	Url string `json:"url,omitempty"`
	Headers *interface{} `json:"headers,omitempty"`
}
