/*
 * Hivelocity API
 *
 * Interact with Hivelocity
 *
 * API version: 2.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

import (
	"time"
)

type Cancellation struct {
	Id int32 `json:"id,omitempty"`
	MonthlyPayment int32 `json:"monthlyPayment,omitempty"`
	DeletedAt time.Time `json:"deletedAt,omitempty"`
	ClientId int32 `json:"clientId,omitempty"`
	ActiveMonths int32 `json:"activeMonths,omitempty"`
	DeviceId int32 `json:"deviceId,omitempty"`
	PlanId int32 `json:"planId,omitempty"`
	Cancelled bool `json:"cancelled,omitempty"`
	RequestDate time.Time `json:"requestDate,omitempty"`
	ServiceId int32 `json:"serviceId,omitempty"`
	Name string `json:"name,omitempty"`
	StartDate time.Time `json:"startDate,omitempty"`
}
