/*
 * Hivelocity API
 *
 * Interact with Hivelocity
 *
 * API version: 2.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type Client struct {
	Company string `json:"company,omitempty"`
	Zip string `json:"zip,omitempty"`
	City string `json:"city,omitempty"`
	Id float32 `json:"id,omitempty"`
	First string `json:"first,omitempty"`
	Country string `json:"country,omitempty"`
	IsClient bool `json:"isClient,omitempty"`
	MetaData interface{} `json:"metaData,omitempty"`
	Login string `json:"login,omitempty"`
	FullName string `json:"fullName,omitempty"`
	State string `json:"state,omitempty"`
	Last string `json:"last,omitempty"`
	Email string `json:"email,omitempty"`
}
