/*
 * Hivelocity API for Partners
 *
 * Interact with Hivelocity
 *
 * API version: 2.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type IpmiLoginData struct {
	Username string `json:"username,omitempty"`
	Drivertype string `json:"drivertype,omitempty"`
	Password string `json:"password,omitempty"`
	Host string `json:"host,omitempty"`
}
