/*
 * Hivelocity API
 *
 * Interact with Hivelocity
 *
 * API version: 2.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type BasicProfile struct {
	FullName *interface{} `json:"full_name,omitempty"`
	Zip *interface{} `json:"zip,omitempty"`
	Last string `json:"last,omitempty"`
	Id int32 `json:"id,omitempty"`
	Login string `json:"login,omitempty"`
	First string `json:"first,omitempty"`
	State *interface{} `json:"state,omitempty"`
	Country *interface{} `json:"country,omitempty"`
	Email string `json:"email,omitempty"`
	IsClient bool `json:"is_client,omitempty"`
	City *interface{} `json:"city,omitempty"`
	Company *interface{} `json:"company,omitempty"`
	MetaData *interface{} `json:"meta_data,omitempty"`
}
