/*
 * Hivelocity API
 *
 * Interact with Hivelocity
 *
 * API version: 2.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ARecordReturn struct {
	Ttl int32 `json:"ttl"`
	Name string `json:"name"`
	DomainId int32 `json:"domainId"`
	Type_ string `json:"type"`
	Addresses []RecordValue `json:"addresses"`
}
