/*
 * Hivelocity API for Partners
 *
 * Interact with Hivelocity
 *
 * API version: 2.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type Vlan struct {
	VlanTag int32 `json:"vlanTag,omitempty"`
	VlanNum int32 `json:"vlanNum,omitempty"`
	VlanId int32 `json:"vlanId,omitempty"`
	PendingDevices []int32 `json:"pendingDevices,omitempty"`
	Description string `json:"description,omitempty"`
	FacilityCode string `json:"facilityCode,omitempty"`
	DeviceIds []int32 `json:"deviceIds,omitempty"`
}
